name: high desert projections
favicon: null
layout_spectrum: 0.75705
typography_spectrum: 0.91329
title: High Desert Projections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.028174819191917777
  lightness: 0.8360596040729433
  saturation: 0.32437220914289355
  rhythmicContrast: 0.470579095184803
purpose: []
